// GENERATED FILE — do not edit by hand.
// Mirrors server/etl/skills.py; regenerate with `python -m scripts.gen_client_skills`
// after changing the Python rules.
//
// The ETL normalises every skill on ingest and scripts/backfill_skills.py fixes
// older rows, so this is a display-time fallback: it folds casing, filler words
// ("C programming" → "C"), versions, plurals and synonyms onto one spelling.

const CANONICAL: Record<string, string> = {
  "c": "C",
  "c++": "C++",
  "c#": "C#",
  "f#": "F#",
  "go": "Go",
  "golang": "Go",
  "rust": "Rust",
  "ruby": "Ruby",
  "scala": "Scala",
  "swift": "Swift",
  "kotlin": "Kotlin",
  "java": "Java",
  "python": "Python",
  "perl": "Perl",
  "php": "PHP",
  "bash": "Bash",
  "matlab": "MATLAB",
  "objective-c": "Objective-C",
  "objective c": "Objective-C",
  "javascript": "JavaScript",
  "typescript": "TypeScript",
  "assembly": "Assembly",
  "verilog": "Verilog",
  "vhdl": "VHDL",
  "nodejs": "Node.js",
  "node.js": "Node.js",
  "node": "Node.js",
  "reactjs": "React",
  "react.js": "React",
  "react": "React",
  "react native": "React Native",
  "nextjs": "Next.js",
  "next.js": "Next.js",
  "vuejs": "Vue.js",
  "vue.js": "Vue.js",
  "vue": "Vue.js",
  "angular": "Angular",
  "redux": "Redux",
  "graphql": "GraphQL",
  "jquery": "jQuery",
  "material ui": "Material UI",
  "tailwind": "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  "postgresql": "PostgreSQL",
  "postgres": "PostgreSQL",
  "mysql": "MySQL",
  "nosql": "NoSQL",
  "mongodb": "MongoDB",
  "dynamodb": "DynamoDB",
  "redis": "Redis",
  "kafka": "Kafka",
  "elasticsearch": "Elasticsearch",
  "opensearch": "OpenSearch",
  "clickhouse": "ClickHouse",
  "cassandra": "Cassandra",
  "couchbase": "Couchbase",
  "aerospike": "Aerospike",
  "memcached": "Memcached",
  "neo4j": "Neo4j",
  "snowflake": "Snowflake",
  "bigquery": "BigQuery",
  "redshift": "Redshift",
  "databricks": "Databricks",
  "sql server": "SQL Server",
  "delta lake": "Delta Lake",
  "rest": "REST APIs",
  "ci/cd": "CI/CD",
  "cicd": "CI/CD",
  "tcp/udp": "TCP/UDP",
  "tcp/ip": "TCP/IP",
  "http/s": "HTTP/S",
  "oauth": "OAuth",
  "grpc": "gRPC",
  "soap": "SOAP",
  "mqtt": "MQTT",
  "amqp": "AMQP",
  "webhooks": "Webhooks",
  "websockets": "WebSockets",
  "k8s": "Kubernetes",
  "devops": "DevOps",
  "mlops": "MLOps",
  "vxworks": "VxWorks",
  "git": "Git",
  "github": "GitHub",
  "gitlab": "GitLab",
  "github actions": "GitHub Actions",
  "github copilot": "GitHub Copilot",
  "azure devops": "Azure DevOps",
  "jira": "Jira",
  "linux": "Linux",
  "unix": "Unix",
  "windows": "Windows",
  "docker": "Docker",
  "kubernetes": "Kubernetes",
  "jenkins": "Jenkins",
  "terraform": "Terraform",
  "ansible": "Ansible",
  "helm": "Helm",
  "argocd": "ArgoCD",
  "prometheus": "Prometheus",
  "grafana": "Grafana",
  "nginx": "nginx",
  "npm": "npm",
  "webpack": "webpack",
  "tcpdump": "tcpdump",
  "wireshark": "Wireshark",
  "ebpf": "eBPF",
  "qemu": "QEMU",
  "aws": "AWS",
  "azure": "Azure",
  "gcp": "GCP",
  "aws glue": "AWS Glue",
  "aws bedrock": "AWS Bedrock",
  "aws lambda": "AWS Lambda",
  "visual studio": "Visual Studio",
  "visual studio code": "VS Code",
  "vs code": "VS Code",
  "django rest framework": "Django REST Framework",
  "entity framework": "Entity Framework",
  "windows services": "Windows Services",
  "stored procedures": "Stored Procedures",
  "web services": "Web Services",
  "active directory": "Active Directory",
  "linux kernel": "Linux kernel",
  "openai": "OpenAI",
  "anthropic": "Anthropic",
  "claude": "Claude",
  "claude code": "Claude Code",
  "cursor": "Cursor",
  "gemini": "Gemini",
  "chatgpt": "ChatGPT",
  "codex": "Codex",
  "copilot": "GitHub Copilot",
  "azure openai": "Azure OpenAI",
  "azure openai service": "Azure OpenAI",
  "claude agent sdk": "Claude Agent SDK",
  "anthropic claude agent sdk": "Claude Agent SDK",
  "openai agents sdk": "OpenAI Agents SDK",
  "openai api": "OpenAI API",
  "langchain": "LangChain",
  "langgraph": "LangGraph",
  "llamaindex": "LlamaIndex",
  "crewai": "CrewAI",
  "autogen": "AutoGen",
  "pytorch": "PyTorch",
  "tensorflow": "TensorFlow",
  "numpy": "NumPy",
  "pandas": "pandas",
  "scikit-learn": "scikit-learn",
  "matplotlib": "matplotlib",
  "opencv": "OpenCV",
  "cuda": "CUDA",
  "vllm": "vLLM",
  "pydantic": "Pydantic",
  "pytest": "pytest",
  "fastapi": "FastAPI",
  "django": "Django",
  "flask": "Flask",
  "spring": "Spring",
  "spring boot": "Spring Boot",
  "spring security": "Spring Security",
  "play framework": "Play Framework",
  "elastic stack": "Elastic Stack",
  "nestjs": "NestJS",
  "express": "Express",
  "ruby on rails": "Ruby on Rails",
  "asp.net": "ASP.NET",
  ".net": ".NET",
  "dotnet": ".NET",
  "rabbitmq": "RabbitMQ",
  "airflow": "Airflow",
  "spark": "Spark",
  "flink": "Flink",
  "pyspark": "PySpark",
  "selenium": "Selenium",
  "playwright": "Playwright",
  "ms sql": "SQL Server",
  "ms sql server": "SQL Server",
  "ibm mq": "IBM MQ",
  "opc ua": "OPC UA",
  "iec 62304": "IEC 62304",
  "soc 2": "SOC 2",
  "iso 13485": "ISO 13485",
  "iso 27001": "ISO 27001",
  "saas": "SaaS",
  "paas": "PaaS",
  "iaas": "IaaS",
  "ios": "iOS",
  "macos": "macOS",
  "android": "Android",
  "flutter": "Flutter",
  "unity": "Unity",
}

const ACRONYMS: Record<string, string> = {
  "ai": "AI",
  "nlp": "NLP",
  "api": "API",
  "sdk": "SDK",
  "cli": "CLI",
  "ui": "UI",
  "ux": "UX",
  "css": "CSS",
  "html": "HTML",
  "sql": "SQL",
  "json": "JSON",
  "xml": "XML",
  "yaml": "YAML",
  "http": "HTTP",
  "https": "HTTPS",
  "dns": "DNS",
  "tcp": "TCP",
  "udp": "UDP",
  "rest": "REST",
  "rpc": "RPC",
  "aws": "AWS",
  "gcp": "GCP",
  "sap": "SAP",
  "crm": "CRM",
  "erp": "ERP",
  "etl": "ETL",
  "ci": "CI",
  "cd": "CD",
  "qa": "QA",
  "seo": "SEO",
  "ssr": "SSR",
  "orm": "ORM",
  "jwt": "JWT",
  "gpu": "GPU",
  "cpu": "CPU",
  "os": "OS",
  "ide": "IDE",
  "rag": "RAG",
  "mcp": "MCP",
  "oop": "OOP",
  "tdd": "TDD",
  "bdd": "BDD",
  "wpf": "WPF",
  "sqs": "SQS",
  "sns": "SNS",
  "rdma": "RDMA",
  "eda": "EDA",
  "cad": "CAD",
  "hil": "HIL",
  "sil": "SIL",
  "vpc": "VPC",
  "iam": "IAM",
  "ssl": "SSL",
  "tls": "TLS",
  "ssh": "SSH",
  "vpn": "VPN",
  "cdn": "CDN",
  "wcag": "WCAG",
  "rtos": "RTOS",
  "fpga": "FPGA",
  "asic": "ASIC",
  "dsp": "DSP",
  "usb": "USB",
  "uart": "UART",
  "pcie": "PCIE",
  "iot": "IOT",
  "sdlc": "SDLC",
  "solid": "SOLID",
  "apis": "APIs",
  "llms": "LLMs",
  "ids": "IDs",
  "sdks": "SDKs",
}

const ALIASES: Record<string, string> = {
  "c language": "C",
  "ansi c": "C",
  "embedded c": "C",
  "modern c++": "C++",
  "c++11": "C++",
  "c++14": "C++",
  "c++17": "C++",
  "c++20": "C++",
  "c++/stl": "C++",
  "stl": "C++",
  "c#.net": "C#",
  "c# .net": "C#",
  ".net core": ".NET",
  ".net framework": ".NET",
  ".net desktop application development": ".NET",
  "asp.net core": "ASP.NET",
  "asp.net web api": "ASP.NET",
  "asp.net mvc": "ASP.NET",
  "js": "JavaScript",
  "ts": "TypeScript",
  "es6": "JavaScript",
  "es2015": "JavaScript",
  "ecmascript": "JavaScript",
  "html5": "HTML",
  "css3": "CSS",
  "sass": "SASS",
  "scss": "SASS",
  "angularjs": "Angular",
  "python3": "Python",
  "go lang": "Go",
  "shell": "Bash",
  "shell scripting": "Bash",
  "bash scripting": "Bash",
  "powershell scripting": "PowerShell",
  "amazon web services": "AWS",
  "google cloud": "GCP",
  "google cloud platform": "GCP",
  "microsoft azure": "Azure",
  "aws s3": "S3",
  "amazon s3": "S3",
  "aws sqs": "SQS",
  "aws sns": "SNS",
  "aws ec2": "EC2",
  "apache kafka": "Kafka",
  "apache spark": "Spark",
  "apache airflow": "Airflow",
  "apache flink": "Flink",
  "apache tomcat": "Tomcat",
  "ms sql db": "SQL Server",
  "mssql": "SQL Server",
  "microsoft sql server": "SQL Server",
  "t-sql": "SQL Server",
  "kubernetes (k8s)": "Kubernetes",
  "k8s operators": "Kubernetes",
  "kubernetes operators": "Kubernetes",
  "artificial intelligence": "AI",
  "ml": "Machine learning",
  "machine learning (ml)": "Machine learning",
  "ai/ml": "Machine learning",
  "deep learning": "Deep learning",
  "llm": "LLMs",
  "large language models": "LLMs",
  "large language models (llms)": "LLMs",
  "llm apis": "LLMs",
  "llm integration": "LLMs",
  "natural language processing": "NLP",
  "computer vision (cv)": "Computer vision",
  "generative ai": "Generative AI",
  "genai": "Generative AI",
  "gen ai": "Generative AI",
  "retrieval augmented generation": "RAG",
  "retrieval-augmented generation": "RAG",
  "model context protocol": "MCP",
  "agent-to-agent protocol": "A2A",
  "ai agents": "AI agents",
  "agentic ai": "AI agents",
  "autonomous agents": "AI agents",
  "agentic systems": "AI agents",
  "agentic architectures": "AI agents",
  "agent frameworks": "AI agent frameworks",
  "agentic frameworks": "AI agent frameworks",
  "agentic ai frameworks": "AI agent frameworks",
  "agentic workflows": "AI agent workflows",
  "agentic flows": "AI agent workflows",
  "agent orchestration": "AI agent workflows",
  "ai agent orchestration": "AI agent workflows",
  "ai coding tools": "AI coding tools",
  "ai coding": "AI coding tools",
  "ai coding agents": "AI coding tools",
  "ai development tools": "AI coding tools",
  "ai-assisted coding tools": "AI coding tools",
  "ai-assisted development": "AI coding tools",
  "ai-assisted development tools": "AI coding tools",
  "ai-assisted software development": "AI coding tools",
  "ai-assisted development workflows": "AI coding tools",
  "ai-powered development tools": "AI coding tools",
  "ai-powered developer tools": "AI coding tools",
  "ai-native coding tools": "AI coding tools",
  "ai-driven development": "AI coding tools",
  "ai-first development": "AI coding tools",
  "ai-assisted workflows": "AI coding tools",
  "ai code assistance tools": "AI coding tools",
  "ai-assisted coding": "AI coding tools",
  "agentic coding": "AI coding tools",
  "vector db": "Vector databases",
  "vector stores": "Vector databases",
  "embeddings": "Embeddings",
  "distributed computing": "Distributed systems",
  "distributed systems design": "Distributed systems",
  "distributed architecture": "Distributed systems",
  "micro-services": "Microservices",
  "microservices architecture": "Microservices",
  "microservices architecture design": "Microservices",
  "microservice architecture": "Microservices",
  "software design": "Software architecture",
  "software design and architecture": "Software architecture",
  "software architecture design": "Software architecture",
  "architecture": "Software architecture",
  "architecture design": "Software architecture",
  "system architecture": "Software architecture",
  "software design principles": "Software design principles",
  "design principles": "Software design principles",
  "solid principles": "SOLID",
  "scalable system design": "System design",
  "scalable systems design": "System design",
  "large-scale system architecture": "System design",
  "large-scale systems": "Scalable systems",
  "high-scale systems": "Scalable systems",
  "scalable systems": "Scalable systems",
  "scalability": "Scalable systems",
  "event driven architecture": "Event-driven architecture",
  "event-driven systems": "Event-driven architecture",
  "cloud native architecture": "Cloud-native architecture",
  "cloud-native technologies": "Cloud-native architecture",
  "serverless architecture": "Serverless",
  "object oriented programming": "OOP",
  "object-oriented programming": "OOP",
  "object-oriented design": "OOP",
  "object oriented design": "OOP",
  "object-oriented analysis and design": "OOP",
  "ood": "OOP",
  "design patterns": "Design patterns",
  "async design patterns": "Design patterns",
  "back-end development": "Backend development",
  "backend engineering": "Backend development",
  "backend software development": "Backend development",
  "backend software engineering": "Backend development",
  "backend programming": "Backend development",
  "backend server programming": "Backend development",
  "backend/server-side development": "Backend development",
  "server-side development": "Backend development",
  "backend services": "Backend development",
  "backend systems": "Backend development",
  "front-end development": "Frontend development",
  "front end development": "Frontend development",
  "back end development": "Backend development",
  "frontend engineering": "Frontend development",
  "front-end engineering": "Frontend development",
  "client-side development": "Frontend development",
  "full stack": "Full-stack development",
  "fullstack": "Full-stack development",
  "full stack development": "Full-stack development",
  "fullstack development": "Full-stack development",
  "full-stack engineering": "Full-stack development",
  "software engineering": "Software development",
  "software development life cycle": "SDLC",
  "web application development": "Web development",
  "web applications": "Web development",
  "mobile app development": "Mobile development",
  "mobile application development": "Mobile development",
  "embedded software": "Embedded systems",
  "embedded development": "Embedded systems",
  "embedded programming": "Embedded systems",
  "embedded software development": "Embedded systems",
  "embedded systems development": "Embedded systems",
  "firmware": "Firmware development",
  "kernel development": "Linux kernel",
  "linux kernel development": "Linux kernel",
  "real time systems": "Real-time systems",
  "realtime systems": "Real-time systems",
  "real-time software development": "Real-time systems",
  "real-time operating systems": "RTOS",
  "low level development": "Low-level development",
  "system-level programming": "Low-level development",
  "systems programming": "Low-level development",
  "agile development": "Agile",
  "agile methodologies": "Agile",
  "agile methodology": "Agile",
  "agile methods": "Agile",
  "agile development methodologies": "Agile",
  "agile practices": "Agile",
  "continuous integration": "CI/CD",
  "continuous delivery": "CI/CD",
  "continuous deployment": "CI/CD",
  "continuous integration/continuous deployment": "CI/CD",
  "code reviews": "Code review",
  "peer review": "Code review",
  "peer code review": "Code review",
  "test automation": "Test automation",
  "automated testing": "Test automation",
  "automation testing": "Test automation",
  "automated tests": "Test automation",
  "automated testing frameworks": "Test automation",
  "testing frameworks": "Test automation",
  "unit tests": "Unit testing",
  "integration tests": "Integration testing",
  "software testing": "Testing",
  "test-driven development": "TDD",
  "test driven development": "TDD",
  "behavior-driven development": "BDD",
  "infrastructure-as-code": "Infrastructure as code",
  "iac": "Infrastructure as code",
  "source control": "Version control",
  "version control systems": "Version control",
  "technical documentation": "Technical documentation",
  "documentation": "Technical documentation",
  "clean code": "Code quality",
  "code quality standards": "Code quality",
  "best practices": "Software development best practices",
  "leadership": "Team leadership",
  "team lead experience": "Team leadership",
  "mentoring": "Mentoring",
  "mentorship": "Mentoring",
  "problem-solving": "Problem solving",
  "problem solving skills": "Problem solving",
  "analytical skills": "Problem solving",
  "troubleshooting": "Debugging",
  "debugging skills": "Debugging",
  "debugging tools": "Debugging",
  "root cause analysis": "Debugging",
  "multi-threading": "Multithreading",
  "multi threading": "Multithreading",
  "multithreaded programming": "Multithreading",
  "multi-threaded programming": "Multithreading",
  "multi-threading programming": "Multithreading",
  "multithreaded systems": "Multithreading",
  "multi-threaded systems": "Multithreading",
  "threading": "Multithreading",
  "concurrent programming": "Concurrency",
  "concurrency control": "Concurrency",
  "async programming": "Asynchronous programming",
  "async/concurrent programming": "Asynchronous programming",
  "asynchronous processing": "Asynchronous programming",
  "async processing": "Asynchronous programming",
  "performance tuning": "Performance optimization",
  "performance improvements": "Performance optimization",
  "optimization": "Performance optimization",
  "latency optimization": "Performance optimization",
  "code profiling": "Performance profiling",
  "performance engineering": "Performance optimization",
  "caching solutions": "Caching",
  "caching strategies": "Caching",
  "rdbms": "Relational databases",
  "relational database": "Relational databases",
  "sql databases": "Relational databases",
  "non-relational databases": "NoSQL",
  "nosql databases": "NoSQL",
  "database optimization": "Query optimization",
  "sql optimization": "Query optimization",
  "sql queries": "SQL",
  "data pipeline": "Data pipelines",
  "etl processes": "ETL",
  "etl pipelines": "ETL",
  "big data": "Big data",
  "message brokers": "Message queues",
  "messaging systems": "Message queues",
  "messaging technologies": "Message queues",
  "queues": "Message queues",
  "data modelling": "Data modeling",
  "networks": "Networking",
  "networking concepts": "Networking",
  "networking fundamentals": "Networking",
  "computer networking": "Networking",
  "networking protocols": "Network protocols",
  "networking concepts and protocols": "Network protocols",
  "communication protocols": "Network protocols",
  "information security": "Cybersecurity",
  "infosec": "Cybersecurity",
  "cyber security": "Cybersecurity",
  "containers": "Containerization",
  "containerisation": "Containerization",
  "container orchestration": "Kubernetes",
  "cloud": "Cloud computing",
  "cloud platforms": "Cloud computing",
  "cloud environments": "Cloud computing",
  "cloud technologies": "Cloud computing",
  "cloud systems": "Cloud computing",
  "cloud-based systems": "Cloud computing",
  "cloud infrastructure": "Cloud computing",
  "cloud computing infrastructure": "Cloud computing",
  "monitoring systems": "Monitoring",
  "production monitoring": "Monitoring",
  "performance monitoring": "Monitoring",
  "alerting systems": "Monitoring",
  "operating system": "Operating systems",
  "os fundamentals": "Operating systems",
  "restful": "REST APIs",
  "rest api": "REST APIs",
  "rest apis": "REST APIs",
  "restful api": "REST APIs",
  "restful apis": "REST APIs",
  "restful services": "REST APIs",
  "rest services": "REST APIs",
  "api": "APIs",
  "api development": "API design",
  "api design and development": "API design",
  "api integrations": "API integration",
  "third-party service integrations": "API integration",
}

const PREFERRED_NUMBER: Record<string, string> = {
  "systems": "systems",
  "system": "systems",
  "tools": "tools",
  "tool": "tools",
  "frameworks": "frameworks",
  "framework": "frameworks",
  "databases": "databases",
  "database": "databases",
  "protocols": "protocols",
  "protocol": "protocols",
  "services": "services",
  "service": "services",
  "pipelines": "pipelines",
  "pipeline": "pipelines",
  "applications": "applications",
  "application": "applications",
  "platforms": "platforms",
  "platform": "platforms",
  "methodologies": "methodologies",
  "methodology": "methodologies",
  "practices": "practices",
  "practice": "practices",
  "principles": "principles",
  "principle": "principles",
  "algorithms": "algorithms",
  "algorithm": "algorithms",
  "patterns": "patterns",
  "pattern": "patterns",
  "workflows": "workflows",
  "workflow": "workflows",
  "agents": "agents",
  "agent": "agents",
  "queues": "queues",
  "queue": "queues",
  "drivers": "drivers",
  "driver": "drivers",
  "technologies": "technologies",
  "technology": "technologies",
  "environments": "environments",
  "environment": "environments",
  "structures": "structures",
  "structure": "structures",
  "languages": "languages",
  "language": "languages",
  "libraries": "libraries",
  "library": "libraries",
  "concepts": "concepts",
  "concept": "concepts",
  "brokers": "brokers",
  "broker": "brokers",
  "solutions": "solutions",
  "solution": "solutions",
  "processes": "processes",
  "processe": "processes",
  "standards": "standards",
  "standard": "standards",
  "architecture": "architecture",
  "architectures": "architecture",
  "development": "development",
  "developments": "development",
  "engineering": "engineering",
  "engineerings": "engineering",
  "design": "design",
  "designs": "design",
  "testing": "testing",
  "testings": "testing",
  "optimization": "optimization",
  "optimizations": "optimization",
  "management": "management",
  "managements": "management",
  "monitoring": "monitoring",
  "monitorings": "monitoring",
  "learning": "learning",
  "learnings": "learning",
  "review": "review",
  "reviews": "review",
  "scripting": "scripting",
  "scriptings": "scripting",
  "networking": "networking",
  "networkings": "networking",
  "computing": "computing",
  "computings": "computing",
  "storage": "storage",
  "storages": "storage",
  "analysis": "analysis",
  "analysiss": "analysis",
  "modeling": "modeling",
  "modelings": "modeling",
  "quality": "quality",
  "qualitys": "quality",
  "documentation": "documentation",
  "documentations": "documentation",
  "leadership": "leadership",
  "leaderships": "leadership",
  "mentoring": "mentoring",
  "mentorings": "mentoring",
  "debugging": "debugging",
  "debuggings": "debugging",
  "deployment": "deployment",
  "deployments": "deployment",
  "automation": "automation",
  "automations": "automation",
  "orchestration": "orchestration",
  "orchestrations": "orchestration",
  "virtualization": "virtualization",
  "virtualizations": "virtualization",
}

const COMMON_WORDS = new Set([
  "a",
  "agent",
  "agents",
  "algorithm",
  "algorithms",
  "an",
  "analysis",
  "analytics",
  "and",
  "application",
  "applications",
  "architecture",
  "architectures",
  "as",
  "assisted",
  "assurance",
  "at",
  "automation",
  "aware",
  "based",
  "basics",
  "best",
  "broker",
  "brokers",
  "capabilities",
  "code",
  "coding",
  "computing",
  "concept",
  "concepts",
  "containerization",
  "critical",
  "cross",
  "database",
  "databases",
  "delivery",
  "deployment",
  "design",
  "designs",
  "developer",
  "developers",
  "development",
  "distributed",
  "driven",
  "driver",
  "drivers",
  "ecosystem",
  "enabled",
  "end",
  "engineering",
  "environment",
  "environments",
  "experience",
  "facing",
  "first",
  "for",
  "framework",
  "frameworks",
  "free",
  "fundamentals",
  "grade",
  "hardware",
  "high",
  "in",
  "infrastructure",
  "integration",
  "integrations",
  "internals",
  "kernel",
  "knowledge",
  "language",
  "languages",
  "learning",
  "level",
  "libraries",
  "library",
  "lifecycle",
  "low",
  "management",
  "method",
  "methodologies",
  "methodology",
  "methods",
  "modeling",
  "modelling",
  "modern",
  "monitoring",
  "multi",
  "native",
  "networking",
  "observability",
  "of",
  "on",
  "open",
  "operations",
  "optimisation",
  "optimization",
  "or",
  "orchestration",
  "oriented",
  "party",
  "pattern",
  "patterns",
  "performance",
  "pipeline",
  "pipelines",
  "platform",
  "platforms",
  "powered",
  "practice",
  "practices",
  "principle",
  "principles",
  "process",
  "processes",
  "programming",
  "protocol",
  "protocols",
  "quality",
  "queue",
  "queues",
  "ready",
  "real",
  "related",
  "review",
  "reviews",
  "safe",
  "scalable",
  "scale",
  "science",
  "scripting",
  "security",
  "service",
  "services",
  "side",
  "skills",
  "software",
  "solution",
  "solutions",
  "source",
  "specific",
  "stack",
  "standards",
  "storage",
  "structure",
  "structures",
  "system",
  "systems",
  "technologies",
  "technology",
  "term",
  "test",
  "testing",
  "tests",
  "the",
  "thread",
  "threaded",
  "threading",
  "time",
  "to",
  "tooling",
  "tools",
  "virtualization",
  "vision",
  "web",
  "with",
  "workflow",
  "workflows",
])

const NO_SPLIT = new Set([
  "and/or",
  "ci/cd",
  "http/s",
  "i/o",
  "r&d",
  "tcp/ip",
  "tcp/udp",
  "ui/ux",
])

const NOISE_SUFFIXES = [
  "development",
  "programming",
  "coding",
  "experience",
  "expertise",
  "knowledge",
  "proficiency",
  "skills",
  "skill",
  "fundamentals",
  "basics",
  "ecosystem",
  "language",
  "stack",
  "technologies",
  "technology",
  "tools",
  "tooling",
  "pipelines",
  "processes",
  "practices",
  "platforms",
  "services",
  "frameworks",
  "environments",
  "solutions",
]

const PREFIX = new RegExp("^(?:(?:strong|excellent|proven|hands[- ]on|in[- ]depth|practical|extensive|solid|working|prior|demonstrated|significant)\\s+|(?:(?:deep|good|basic|advanced|strong|solid)\\s+)?(?:experience|expertise|proficiency|proficient|familiarity|background|understanding|knowledge|fluency)\\s+(?:with|in|of|using|as)\\s+|(?:ability|willingness)\\s+to\\s+)", 'i')


const TECH_NAMES = new Set([...Object.keys(CANONICAL), ...Object.keys(ACRONYMS)])

const WS = /\s+/g
const PARENS = /\s*\([^)]*\)/g
const VERSION = /\s+v?\d+(?:\.\d+)*\+?$/
const UPPER = /[A-Z]/
const INNER_UPPER = /.[A-Z]/

function clean(raw: string): string {
  let skill = String(raw).replace(/\u00a0/g, ' ').replace(WS, ' ').trim()
  skill = skill.replace(/^["'`\u201c\u201d\u2018\u2019]+|["'`\u201c\u201d\u2018\u2019]+$/g, '').trim()
  const stripped = skill.replace(PARENS, '').trim()
  if (stripped) skill = stripped
  skill = skill.replace(/ & /g, ' and ').replace(/[.,;:]+$/, '').trim()
  return skill.replace(WS, ' ')
}

function stripPrefix(skill: string): string {
  for (;;) {
    const low = skill.toLowerCase()
    if (low in ALIASES || low in CANONICAL) return skill
    const trimmed = skill.replace(PREFIX, '').trim()
    if (trimmed === skill || !trimmed) return skill
    skill = trimmed
  }
}

function stripSuffix(skill: string): string {
  for (;;) {
    const low = skill.toLowerCase()
    let head: string | null = null
    for (const suffix of NOISE_SUFFIXES) {
      if (low.endsWith(' ' + suffix)) {
        head = skill.slice(0, -(suffix.length + 1)).trim()
        break
      }
    }
    if (head === null) {
      const versioned = skill.replace(VERSION, '').trim()
      if (versioned !== skill) head = versioned
    }
    if (!head) return skill
    const headLow = head.toLowerCase()
    if (headLow in ALIASES) return ALIASES[headLow]
    if (!TECH_NAMES.has(headLow)) return skill
    skill = head
  }
}

function recaseToken(token: string, isFirst: boolean, casingOnly = false): string {
  const low = token.toLowerCase()
  const canonical = CANONICAL[low]
  if (canonical && !canonical.includes(' ') && !(casingOnly && canonical.toLowerCase() !== low)) {
    return canonical
  }
  if (token.includes('-') && token.length > 1) {
    return token
      .split('-')
      .map((part, i) => recaseToken(part, isFirst && i === 0, true))
      .join('-')
  }
  if (token !== token.toUpperCase() && INNER_UPPER.test(token)) return token
  if (ACRONYMS[low]) return ACRONYMS[low]
  if (!token) return token
  if (isFirst) return UPPER.test(token) ? token : low.charAt(0).toUpperCase() + low.slice(1)
  if (COMMON_WORDS.has(low)) return low
  if (UPPER.test(token)) return token
  return low
}

function recase(skill: string): string {
  let words = skill.split(' ')
  if (words.length > 1 && skill === skill.toUpperCase() && words.some(w => w.length >= 5)) {
    words = skill.toLowerCase().split(' ')
  }
  return words.map((w, i) => recaseToken(w, i === 0)).join(' ')
}

function fixLastWord(skill: string): string {
  const words = skill.split(' ')
  if (words.length < 2) return skill
  const last = words[words.length - 1]
  if (last === last.toLowerCase() && PREFERRED_NUMBER[last]) {
    words[words.length - 1] = PREFERRED_NUMBER[last]
  }
  return words.join(' ')
}

function resolve(skill: string): string {
  skill = ALIASES[skill.toLowerCase()] ?? skill
  const canonical = CANONICAL[skill.toLowerCase()]
  if (canonical) return canonical
  skill = stripSuffix(skill)
  skill = ALIASES[skill.toLowerCase()] ?? skill
  const canonical2 = CANONICAL[skill.toLowerCase()]
  if (canonical2) return canonical2
  skill = fixLastWord(recase(skill))
  return ALIASES[skill.toLowerCase()] ?? skill
}

/** Canonical display spelling of one skill string. */
export function formatSkill(raw: string): string {
  let skill = stripPrefix(clean(raw))
  if (!skill) return ''
  for (let i = 0; i < 3; i++) {
    const next = resolve(skill)
    if (next === skill) break
    skill = next
  }
  return skill
}

/**
 * Normalise one skill string into the skills it actually names — compounds
 * whose sides are technologies in their own right are split ("C/C++" → C, C++),
 * names that merely contain a slash ("CI/CD") are left whole.
 */
export function expandSkill(raw: string): string[] {
  const skill = stripPrefix(clean(raw))
  if (!skill) return []
  const low = skill.toLowerCase()
  if (skill.includes('/') && !skill.includes(' ') && !NO_SPLIT.has(low) && !(low in CANONICAL)) {
    const parts = skill.split('/').map(p => p.trim()).filter(Boolean)
    if (
      parts.length > 1 &&
      parts.every(p => TECH_NAMES.has(p.toLowerCase()) || p.toLowerCase() in ALIASES)
    ) {
      const out: string[] = []
      for (const part of parts) {
        const norm = formatSkill(part)
        if (norm && !out.includes(norm)) out.push(norm)
      }
      return out
    }
  }
  const norm = formatSkill(skill)
  return norm ? [norm] : []
}
